import { Document, Page, Text, View } from "@react-pdf/renderer"
import type { CVScorePayload } from "@/types/api.types"
import { pdfStyles } from "./styles"

function BulletList({ items }: { items: string[] }) {
  if (!items.length) return null
  return (
    <View>
      {items.map((line, i) => (
        <View key={i} style={pdfStyles.bullet} wrap={false}>
          <Text style={pdfStyles.bulletDot}>• </Text>
          <Text style={pdfStyles.bulletText}>{line}</Text>
        </View>
      ))}
    </View>
  )
}

export interface CVScorePdfDocumentProps {
  payload: CVScorePayload
  resumeLabel?: string | null
  generatedAt?: string
}

export function CVScorePdfDocument({
  payload,
  resumeLabel,
  generatedAt,
}: CVScorePdfDocumentProps) {
  const scored =
    payload.scored_at != null
      ? (() => {
          try {
            return new Date(payload.scored_at).toLocaleString()
          } catch {
            return payload.scored_at
          }
        })()
      : null

  const breakdownEntries = Object.entries(payload.breakdown ?? {})

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.title}>CV score report</Text>
        <Text style={pdfStyles.subtitle}>Crackint — exported report</Text>

        {resumeLabel ? (
          <Text style={pdfStyles.metaRow}>Resume: {resumeLabel}</Text>
        ) : null}
        {scored ? <Text style={pdfStyles.metaRow}>Scored: {scored}</Text> : null}
        {generatedAt ? (
          <Text style={pdfStyles.metaRow}>Exported: {generatedAt}</Text>
        ) : null}

        <Text style={pdfStyles.sectionTitle}>Overall score</Text>
        <Text style={pdfStyles.body}>{Math.round(payload.score)} / 100</Text>

        {breakdownEntries.length > 0 ? (
          <>
            <Text style={pdfStyles.sectionTitle}>Breakdown</Text>
            {breakdownEntries.map(([key, val]) => (
              <Text key={key} style={[pdfStyles.body, { marginBottom: 3 }]}>
                {key}: {typeof val === "number" ? Math.round(val) : String(val)}
              </Text>
            ))}
          </>
        ) : null}

        {payload.suggestions.length > 0 ? (
          <>
            <Text style={pdfStyles.sectionTitle}>Suggestions</Text>
            <BulletList items={payload.suggestions} />
          </>
        ) : null}

        <Text style={pdfStyles.footerNote} fixed>
          Generated by Crackint — interview preparation
        </Text>
      </Page>
    </Document>
  )
}
